name: Itch.io Deploy Workflow
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

    # Optionally, you can set other parameters like 'notes' or 'draft'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Upload to itch.io
      uses: robpc/itchio-upload-action@v1
      with:
        path: .
        project: genjunji/ligamabol-1
        channel: windows
        api-key: ${{ secrets.ITCHIO_API_KEY }}
